# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on: push

jobs:
  build:

    runs-on: [self-hosted, qa]

    steps:
    
    - name: Change ENV VARIABLES
      run: |
        $env:DATABASE_URL="10.43.100.194:33061"
        $env:DATABASE_USERNAME="root"
        $env:DATABASE_PASSWORD="secret"

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.2
        
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Run program
      run: java -jar target/bottomline-0.0.1-SNAPSHOT.jar
